image: macOS

branches:
  only:
  - appveyor-mac


skip_commits:
  files:
    - '*.md'
    - docs/*

install:
  - echo "INSTALL"
  - brew install qt p7zip
  - brew link qt --force
  - which qmake

before_build:
  - qmake --version 
  - python3 --version
  - pip3 freeze > requirements.txt
  - pip3 install -r requirements.txt
  - sudo pip3 install --upgrade oauth2client
  - sudo pip3 install --upgrade google-api-python-client

build_script:
  - mkdir "build"
  - cd build
  - qmake ../ PREFIX=/usr CONFIG+=release CONFIG+=GIT CONFIG+=PENCIL2D_NIGHTLY
  - make

after_build:
  - echo "cleaning..."
  - make clean
  - mv bin Pencil2D
  - cd Pencil2D

  - echo "Copying ffmpeg plugin"
  - mkdir Pencil2D.app/Contents/MacOS/plugins
  - curl -fsSLo ffmpeg.7z https://evermeet.cx/ffmpeg/getrelease/7z
  - curl -fsSLo ffmpeg.7z.sig https://evermeet.cx/ffmpeg/getrelease/7z/sig
  - echo "trusted-key 0x476C4B611A660874" > ~/.gnupg/gpg.conf
  - curl -fsSL https://evermeet.cx/ffmpeg/0x1A660874.asc | gpg --import
  - gpg --verify ffmpeg.7z.sig ffmpeg.7z
  - 7z x ffmpeg.7z -o"Pencil2D.app/Contents/MacOS/plugins"
  - rm ffmpeg.7z ffmpeg.7z.sig

  - echo "Copying necessary Qt frameworks"
  - macdeployqt Pencil2D.app
  - echo "applying macdeployqt fix"
  - curl -fsSLO https://github.com/aurelien-rainone/macdeployqtfix/archive/master.zip
  - unzip -x master.zip
  - python macdeployqtfix-master/macdeployqtfix.py Pencil2D.app/Contents/MacOS/Pencil2D /usr/local/Cellar/qt/5.9.1/
  - echo "Removing files"
  - rm -rf macdeployqtfix-master
  - rm master.zip
  
  - cd ..
  - echo "Zipping..."
  - zip -r "pencil2d-mac-$(date +"%Y-%m-%d").zip" Pencil2D/
  - echo "zipping done"
  - pwd
  - ls

test_script:
  - ./tests/tests

deploy_script:
  - echo "Initiate deployment on Google Drive"
  - pwd
  - ls
  - cd ../util
  - pwd
  - ls
  - python3 nightly-build-upload.py "$OSX_NIGHTLY_PARENT" "../build/pencil2d-mac-$(date +"%Y-%m-%d").zip";
  - echo "Operation done";